### ISSUE TITLE
Reduce shadow variances to 1

### ISSUE THREAD

**Issue by GeorgeTaveras1231** [xogroup/union#277]
Replace all `box-shadow` properties for:

```scss
.a-class {
  composes: shadow from '@xo-union/tk-css-utilities/lib/effects';
}
```

In `@xo-union/tk-css-utilities/lib/effects`. Shaddow should be defined as:

```scss
.shadow {
  box-shadow: 1px 1px 4px 0 rgba(179,178,178,0.5);
}
```

This is a temporary solution to: #262
