### ISSUE TITLE
mint-lighter-70 is blue

### ISSUE THREAD

**Issue by gsheppard** [xogroup/union#293]
Context
===

- [x] Visual bug?
- [ ] Runtime bug?
- [ ] Build bug?

### *package name(s) and versions*
`@xo-union/tk-css-colors@2.1.0`

Issue
===
The `mint-lighter-70` color is not mint, but is rather a light blue color.

[color definitions](https://github.com/xogroup/union/blob/master/packages/%40xo-union/tk-css-colors/src/_color_definitions.scss#L117)

![screen shot 2017-08-15 at 4 24 47 pm](https://user-images.githubusercontent.com/4898984/29334957-246c47c2-81d7-11e7-9c8c-fe2533946f66.png)
![screen shot 2017-08-15 at 4 31 20 pm](https://user-images.githubusercontent.com/4898984/29334980-32a708d6-81d7-11e7-83f3-d0d5fc89032f.png)

**Comment by gsheppard** [comment]
I would just fix it and open a PR, but I don't know what tool/process you're using to determine the exact hex value. (tbh I thought you were just using the SASS `lighten` function)

**Comment by GeorgeTaveras1231** [comment]
@gsheppard we can probably look into using this function but the implementation of this module pre-dates Core Front End, this was something implemented by Phill Kelly and Silvia. Since these values are hardcoded, we can probably get the intended value from the design ui kit. @madelinehvu  can probably help provide the value.

**Comment by gsheppard** [comment]
If you do, the colors will change. Some quick research using the `lighten` function to replicate the colors provided shows that the difference between each stage in _our_ colors equates to _roughly_ a 3% shade difference for the `lighten` function. But usually about 0.1-0.2% off.

```scss
$mint: #8fd5b6;
.mint {
  &.lighter-50 { 
    color: lighten($mint, 15%);
  }
  &.lighter-40 { 
    color: lighten($mint, 11.8%);
  }
  &.lighter-30 { 
    color: lighten($mint, 8.9%);
  }
  &.lighter-20 { 
    color: lighten($mint, 5.9%);
  }
  &.lighter-10 { 
    color: lighten($mint, 3%);
  }
}
```
